"""Standalone dbt project execution for eltPulse managed workers."""

from __future__ import annotations

import asyncio
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Callable, Awaitable

PatchFn = Callable[[dict[str, Any]], Awaitable[None]]


def _sanitize_profile_name(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_-]", "_", name.strip()) or "eltpulse"


def _schema_from_ctx(dbt_cfg: dict[str, Any], target_schema: str | None) -> str:
    if target_schema and target_schema.strip():
        return target_schema.strip()
    ds = dbt_cfg.get("dataset_name") or dbt_cfg.get("target_schema")
    if isinstance(ds, str) and ds.strip():
        return ds.strip()
    return "public"


def build_profiles_yml(
    profile_name: str,
    connector: str,
    target_schema: str | None,
    dbt_cfg: dict[str, Any],
) -> str | None:
    name = _sanitize_profile_name(profile_name)
    schema = _schema_from_ctx(dbt_cfg, target_schema)
    c = connector.lower()

    if c == "snowflake":
        return f"""# Auto-generated by eltPulse managed worker
{name}:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{{{ env_var('SNOWFLAKE_ACCOUNT') }}}}"
      user: "{{{{ env_var('SNOWFLAKE_USER') }}}}"
      password: "{{{{ env_var('SNOWFLAKE_PASSWORD', '') }}}}"
      private_key: "{{{{ env_var('SNOWFLAKE_PRIVATE_KEY', '') }}}}"
      private_key_passphrase: "{{{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE', '') }}}}"
      role: "{{{{ env_var('SNOWFLAKE_ROLE', '') }}}}"
      database: "{{{{ env_var('SNOWFLAKE_DATABASE') }}}}"
      warehouse: "{{{{ env_var('SNOWFLAKE_WAREHOUSE') }}}}"
      schema: {schema}
      threads: 4
"""

    if c == "bigquery":
        return f"""# Auto-generated by eltPulse managed worker
{name}:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{{{ env_var('GCP_PROJECT_ID') }}}}"
      dataset: {schema}
      keyfile_json: "{{{{ env_var('GCP_CREDENTIALS') }}}}"
      threads: 4
"""

    if c in ("postgres", "postgresql"):
        return f"""# Auto-generated by eltPulse managed worker
{name}:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{{{ env_var('DEST_POSTGRES_HOST', 'localhost') }}}}"
      port: "{{{{ env_var('DEST_POSTGRES_PORT', '5432') | int }}}}"
      user: "{{{{ env_var('DEST_POSTGRES_USER') }}}}"
      password: "{{{{ env_var('DEST_POSTGRES_PASSWORD') }}}}"
      dbname: "{{{{ env_var('DEST_POSTGRES_DATABASE') }}}}"
      schema: {schema}
      threads: 4
"""

    if c == "duckdb":
        return f"""# Auto-generated by eltPulse managed worker
{name}:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{{{ env_var('DEST_DUCKDB_PATH', './data.duckdb') }}}}"
      schema: {schema}
      threads: 4
"""

    if c == "redshift":
        return f"""# Auto-generated by eltPulse managed worker
{name}:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{{{ env_var('REDSHIFT_HOST') }}}}"
      port: "{{{{ env_var('REDSHIFT_PORT', '5439') | int }}}}"
      user: "{{{{ env_var('REDSHIFT_USER') }}}}"
      password: "{{{{ env_var('REDSHIFT_PASSWORD') }}}}"
      dbname: "{{{{ env_var('REDSHIFT_DATABASE') }}}}"
      schema: {schema}
      threads: 4
"""

    return None


def dbt_action_from_triggered_by(triggered_by: str | None) -> str:
    tb = (triggered_by or "").strip()
    if tb.startswith("ui:dbt_compile"):
        return "compile"
    if tb.startswith("ui:dbt_test"):
        return "test"
    return "run"


def dbt_select_args(source_configuration: dict[str, Any]) -> list[str]:
    dbt = source_configuration.get("dbt") or source_configuration.get("dlt_dbt")
    if not isinstance(dbt, dict):
        return []
    selector = str(dbt.get("selector") or "").strip()
    if selector:
        return ["--select", selector]
    return []


def _run_git_clone(git_url: str, branch: str, dest: Path) -> None:
    branch = branch.strip() or "main"
    cmd = ["git", "clone", "--depth", "1", "--branch", branch, git_url, str(dest)]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        # Retry without branch (default branch)
        shutil.rmtree(dest, ignore_errors=True)
        proc = subprocess.run(
            ["git", "clone", "--depth", "1", git_url, str(dest)],
            capture_output=True,
            text=True,
        )
        if proc.returncode != 0:
            raise RuntimeError(f"git clone failed: {proc.stderr[:800]}")


def prepare_dbt_project_dir(
    pipeline: dict[str, Any],
    dbt_project: dict[str, Any] | None,
    work_root: Path,
) -> tuple[Path, str]:
    """Returns (project_dir, profile_name)."""
    sc = pipeline.get("sourceConfiguration") or {}
    if not isinstance(sc, dict):
        sc = {}

    git_url = str(dbt_project.get("gitUrl") or sc.get("dbt", {}).get("git_url") or "").strip()
    if not git_url:
        git_url = str((sc.get("dbt") or {}).get("git_url") or "").strip()

    git_branch = str(
        dbt_project.get("gitBranch")
        or (sc.get("dbt") or {}).get("repository_branch")
        or "main"
    ).strip()
    git_subpath = str(
        dbt_project.get("gitSubpath")
        or (sc.get("dbt") or {}).get("git_subpath")
        or dbt_project.get("packagePath")
        or ""
    ).strip()

    profile_name = _sanitize_profile_name(str(pipeline.get("name") or "eltpulse"))

    if git_url:
        repo_dir = work_root / "repo"
        _run_git_clone(git_url, git_branch, repo_dir)
        project_dir = repo_dir / git_subpath if git_subpath else repo_dir
        if not project_dir.is_dir():
            raise RuntimeError(f"dbt project path not found after clone: {project_dir}")
        return project_dir, profile_name

    package_path = str(
        dbt_project.get("packagePath")
        or (sc.get("dbt") or {}).get("package_path")
        or ""
    ).strip()
    if package_path:
        project_dir = work_root / "project"
        project_dir.mkdir(parents=True, exist_ok=True)
        readme = project_dir / "README.txt"
        readme.write_text(
            f"Local dbt path {package_path!r} is not available on managed workers. "
            "Configure a Git URL on the dbt project.",
            encoding="utf-8",
        )
        raise RuntimeError(
            "dbt project has no Git URL — managed workers require gitUrl on DbtProject"
        )

    raise RuntimeError("No git URL or package path for dbt project")


async def _upload_dbt_artifacts(
    project_dir: Path,
    patch: PatchFn,
) -> None:
    target = project_dir / "target"
    body: dict[str, Any] = {}
    run_results = target / "run_results.json"
    manifest = target / "manifest.json"
    if run_results.is_file():
        body["dbtRunResults"] = json.loads(run_results.read_text(encoding="utf-8"))
    if manifest.is_file():
        body["dbtArtifactManifest"] = json.loads(manifest.read_text(encoding="utf-8"))
    if body:
        await patch(body)


async def execute_standalone_dbt(
    *,
    pipeline: dict[str, Any],
    dbt_project: dict[str, Any] | None,
    destination: dict[str, Any] | None,
    triggered_by: str | None,
    child_env: dict[str, str],
    patch: PatchFn,
    pump_stdout: Callable[[str], Awaitable[None]] | None = None,
    pump_stderr: Callable[[str], Awaitable[None]] | None = None,
) -> int:
    """Clone, profile, deps, run/compile/test. Returns exit code."""
    work_root = Path(tempfile.mkdtemp(prefix="eltpulse-dbt-"))
    try:
        project_dir, profile_name = prepare_dbt_project_dir(pipeline, dbt_project, work_root)

        connector = str(destination.get("connector") if destination else "snowflake").lower()
        target_schema = (
            str(dbt_project.get("targetSchema") or "") if dbt_project else ""
        ) or None
        sc = pipeline.get("sourceConfiguration") or {}
        dbt_cfg = sc.get("dbt") if isinstance(sc, dict) else {}
        if not isinstance(dbt_cfg, dict):
            dbt_cfg = {}

        profiles = build_profiles_yml(profile_name, connector, target_schema, dbt_cfg)
        if not profiles:
            raise RuntimeError(f"Unsupported dbt destination connector: {connector}")

        profiles_path = project_dir / "profiles.yml"
        profiles_path.write_text(profiles, encoding="utf-8")

        action = dbt_action_from_triggered_by(triggered_by)
        select_args = dbt_select_args(sc if isinstance(sc, dict) else {})

        await patch({
            "status": "running",
            "appendLog": {"level": "info", "message": f"dbt: prepared project at {project_dir}"},
            "telemetrySummary": {"currentPhase": "dbt", "progress": 20},
        })

        env = {**child_env, "DBT_PROFILES_DIR": str(project_dir)}

        async def _run_cmd(args: list[str], phase_msg: str) -> int:
            await patch({
                "status": "running",
                "appendLog": {"level": "info", "message": phase_msg},
            })
            proc = await asyncio.create_subprocess_exec(
                *args,
                cwd=str(project_dir),
                env=env,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            assert proc.stdout and proc.stderr

            async def drain(stream: asyncio.StreamReader, label: str) -> None:
                while True:
                    line_b = await stream.readline()
                    if not line_b:
                        break
                    line = line_b.decode("utf-8", errors="replace").rstrip()
                    if not line:
                        continue
                    if label == "stdout" and pump_stdout:
                        await pump_stdout(line)
                    elif label == "stderr" and pump_stderr:
                        await pump_stderr(line)

            await asyncio.gather(
                drain(proc.stdout, "stdout"),
                drain(proc.stderr, "stderr"),
                proc.wait(),
            )
            return proc.returncode if proc.returncode is not None else 1

        dbt_bin = os.environ.get("ELTPULSE_DBT_BIN", "dbt").strip() or "dbt"
        common = [dbt_bin, "--profiles-dir", str(project_dir), "--profile", profile_name, "--target", "dev"]

        deps_code = await _run_cmd(common + ["deps"], "dbt: installing packages (dbt deps)…")
        if deps_code != 0:
            return deps_code

        if action == "compile":
            cmd = common + ["compile", *select_args]
        elif action == "test":
            cmd = common + ["test", *select_args]
        else:
            cmd = common + ["run", *select_args]

        await patch({
            "telemetrySummary": {"currentPhase": "dbt", "progress": 50},
        })
        exit_code = await _run_cmd(cmd, f"dbt: running dbt {action}…")

        if exit_code == 0:
            await _upload_dbt_artifacts(project_dir, patch)
            await patch({"telemetrySummary": {"currentPhase": "done", "progress": 100}})

        return exit_code
    finally:
        shutil.rmtree(work_root, ignore_errors=True)
