import { escapePyString } from "./escape-py";

export const ELTPULSE_PRODUCT_URL = "https://www.eltpulse.dev";
export const ELTPULSE_PIPELINES_DOCS = `${ELTPULSE_PRODUCT_URL}/docs/pipelines`;

const PY3Q = '"""';

/** Top-of-file docstring for exported Python sync runners. */
export function eltpulsePythonModuleHeader(pipelineName: string, description?: string): string {
  const descLine = description ? `\n${escapePyString(description)}` : "";
  return `${PY3Q}eltPulse pipeline: ${escapePyString(pipelineName)}${descLine}
Generated by eltPulse — ${ELTPULSE_PIPELINES_DOCS}
${PY3Q}
`;
}

/** Comment banner for YAML replication exports. */
export function eltpulseYamlFileHeader(): string {
  return `# Generated by eltPulse — ${ELTPULSE_PIPELINES_DOCS}\n`;
}
