/**
 * Generate dbt profiles.yml from eltPulse connection secrets (warehouse destinations).
 * Credentials stay as env_var references — secrets are injected into the worker env.
 */

export type DbtProfileContext = {
  profileName: string;
  connector: string;
  targetSchema?: string | null;
  config?: Record<string, unknown>;
};

function schemaName(ctx: DbtProfileContext): string {
  const fromConfig =
    typeof ctx.config?.schema_name === "string" && ctx.config.schema_name.trim()
      ? ctx.config.schema_name.trim()
      : typeof ctx.config?.target_schema === "string" && ctx.config.target_schema.trim()
        ? ctx.config.target_schema.trim()
        : null;
  return ctx.targetSchema?.trim() || fromConfig || "public";
}

export function buildDbtProfilesYml(ctx: DbtProfileContext): string | null {
  const name = ctx.profileName.replace(/[^a-zA-Z0-9_-]/g, "_") || "eltpulse";
  const connector = ctx.connector.toLowerCase();
  const schema = schemaName(ctx);

  if (connector === "snowflake") {
    return `# Auto-generated by eltPulse managed worker
${name}:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      private_key: "{{ env_var('SNOWFLAKE_PRIVATE_KEY', '') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE', '') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', '') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      schema: ${schema}
      threads: 4
`;
  }

  if (connector === "bigquery") {
    return `# Auto-generated by eltPulse managed worker
${name}:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: ${schema}
      keyfile_json: "{{ env_var('GCP_CREDENTIALS') }}"
      threads: 4
`;
  }

  if (connector === "postgres" || connector === "postgresql") {
    return `# Auto-generated by eltPulse managed worker
${name}:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DEST_POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('DEST_POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('DEST_POSTGRES_USER') }}"
      password: "{{ env_var('DEST_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('DEST_POSTGRES_DATABASE') }}"
      schema: ${schema}
      threads: 4
`;
  }

  if (connector === "duckdb") {
    return `# Auto-generated by eltPulse managed worker
${name}:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DEST_DUCKDB_PATH', './data.duckdb') }}"
      schema: ${schema}
      threads: 4
`;
  }

  if (connector === "redshift") {
    return `# Auto-generated by eltPulse managed worker
${name}:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      port: "{{ env_var('REDSHIFT_PORT', '5439') | int }}"
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      dbname: "{{ env_var('REDSHIFT_DATABASE') }}"
      schema: ${schema}
      threads: 4
`;
  }

  return null;
}

export function dbtActionFromTriggeredBy(triggeredBy: string | null | undefined): "run" | "compile" | "test" {
  const tb = triggeredBy?.trim() ?? "";
  if (tb === "ui:dbt_compile" || tb.startsWith("ui:dbt_compile:")) return "compile";
  if (tb === "ui:dbt_test" || tb.startsWith("ui:dbt_test:")) return "test";
  return "run";
}

export function dbtSelectArgs(sourceConfiguration: unknown): string[] {
  if (!sourceConfiguration || typeof sourceConfiguration !== "object") return [];
  const sc = sourceConfiguration as Record<string, unknown>;
  const dbt = (sc.dbt ?? sc.dlt_dbt) as Record<string, unknown> | undefined;
  if (!dbt) return [];
  const selector = typeof dbt.selector === "string" ? dbt.selector.trim() : "";
  if (selector) return ["--select", selector];
  const scope = String(dbt.run_scope ?? dbt.runScope ?? "all").toLowerCase();
  if (scope === "selection" && selector) return ["--select", selector];
  return [];
}
