/**
 * Per-component esbuild entries for standalone compile.mjs artifacts.
 * id → module path + exported definition symbol
 */
export const PACKAGE_COMPILE_ENTRIES = [
  { id: "join_tables", module: "definitions/join-tables", export: "joinTablesComponent" },
  { id: "filter_rows", module: "definitions/filter-rows", export: "filterRowsComponent" },
  { id: "dq_check", module: "definitions/dq-check", export: "dqCheckComponent" },
  { id: "freshness_check", module: "definitions/freshness-check", export: "freshnessCheckComponent" },
  { id: "sql_transform", module: "definitions/sql-transform", export: "sqlTransformComponent" },
  { id: "select_columns", module: "definitions/select-columns", export: "selectColumnsComponent" },
  { id: "drop_duplicates", module: "definitions/drop-duplicates", export: "dropDuplicatesComponent" },
  { id: "union_tables", module: "definitions/union-tables", export: "unionTablesComponent" },
  { id: "unique_check", module: "definitions/unique-check", export: "uniqueCheckComponent" },
  { id: "rename_columns", module: "definitions/column-ops", export: "renameColumnsComponent" },
  { id: "cast_columns", module: "definitions/column-ops", export: "castColumnsComponent" },
  { id: "group_aggregate", module: "definitions/table-ops", export: "groupAggregateComponent" },
  { id: "sort_rows", module: "definitions/table-ops", export: "sortRowsComponent" },
  { id: "limit_rows", module: "definitions/table-ops", export: "limitRowsComponent" },
  { id: "fill_nulls", module: "definitions/table-ops", export: "fillNullsComponent" },
  { id: "replace_values", module: "definitions/table-ops", export: "replaceValuesComponent" },
  { id: "sample_rows", module: "definitions/table-ops", export: "sampleRowsComponent" },
  { id: "add_column_expr", module: "definitions/table-ops", export: "addColumnExprComponent" },
  { id: "s3_monitor", module: "definitions/sensor-monitors", export: "s3MonitorComponent" },
  { id: "sqs_monitor", module: "definitions/sensor-monitors", export: "sqsMonitorComponent" },
  { id: "gcs_monitor", module: "definitions/sensor-monitors", export: "gcsMonitorComponent" },
  { id: "kafka_monitor", module: "definitions/sensor-monitors", export: "kafkaMonitorComponent" },
  { id: "sql_monitor", module: "definitions/sensor-monitors", export: "sqlMonitorComponent" },
  { id: "s3_to_database_asset", module: "definitions/ingestion-hints", export: "s3IngestComponent" },
  { id: "sqs_to_database_asset", module: "definitions/ingestion-hints", export: "sqsIngestComponent" },
  { id: "kafka_to_database_asset", module: "definitions/ingestion-hints", export: "kafkaIngestComponent" },
  { id: "rest_api_fetcher", module: "definitions/ingestion-hints", export: "restApiIngestComponent" },
  { id: "sql_to_database_asset", module: "definitions/ingestion-hints", export: "sqlToDatabaseComponent" },
  { id: "pivot", module: "definitions/analytics-transforms", export: "pivotComponent" },
  { id: "cross_join", module: "definitions/analytics-transforms", export: "crossJoinComponent" },
  { id: "anti_join", module: "definitions/analytics-transforms", export: "antiJoinComponent" },
  { id: "data_cleansing", module: "definitions/analytics-transforms", export: "dataCleansingComponent" },
  { id: "datetime_parser", module: "definitions/analytics-transforms", export: "datetimeParserComponent" },
  { id: "unpivot", module: "definitions/more-transforms", export: "unpivotComponent" },
  { id: "rank", module: "definitions/more-transforms", export: "rankComponent" },
  { id: "running_total", module: "definitions/more-transforms", export: "runningTotalComponent" },
  { id: "record_id", module: "definitions/more-transforms", export: "recordIdComponent" },
  { id: "text_to_columns", module: "definitions/more-transforms", export: "textToColumnsComponent" },
  { id: "json_flatten", module: "definitions/more-transforms", export: "jsonFlattenComponent" },
  { id: "one_hot_encoding", module: "definitions/more-transforms", export: "oneHotEncodingComponent" },
  { id: "train_test_split", module: "definitions/more-transforms", export: "trainTestSplitComponent" },
  { id: "top_n_per_group", module: "definitions/more-transforms", export: "topNPerGroupComponent" },
  { id: "count_records", module: "definitions/more-transforms", export: "countRecordsComponent" },
  { id: "audit_columns", module: "definitions/more-transforms", export: "auditColumnsComponent" },
  { id: "semi_join", module: "definitions/more-transforms", export: "semiJoinComponent" },
  { id: "gcs_to_database_asset", module: "definitions/ingestion-hints", export: "gcsIngestComponent" },
  { id: "hl7_v2_parser", module: "definitions/domain-parsers", export: "hl7V2ParserComponent" },
  { id: "fix_message_parser", module: "definitions/domain-parsers", export: "fixMessageParserComponent" },
  { id: "email_parser", module: "definitions/domain-parsers", export: "emailParserComponent" },
  { id: "regex_parser", module: "definitions/domain-parsers", export: "regexParserComponent" },
  { id: "html_parser", module: "definitions/domain-parsers", export: "htmlParserComponent" },
] as const;
